name: Build, Test and Deploy - test

on:
  push:
    branches: [test]
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - "**.go"
      - "**.mod"
      - "**.sum"
      - "**.templ"
      - "**.html"
      - "**.css"
      - "**.js"

  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip test suite"
        type: boolean
        default: false

env:
  PROJECT_ID: expense-tracker-481402
  REGION: europe-west1
  SERVICE: expense-tracker

concurrency: production

jobs:
  Build-and-test:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # fetch all history
          filter: blob:none # exclude file contents for faster checkout

      ################################################
      # VERSION
      ################################################
      - name: Bump version and push tag
        id: taggerDryRun
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
          WITH_V: false
          PRERELEASE: false
          DRY_RUN: true

      - name: echo new tag
        run: |
          echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"

      - name: echo tag
        run: |
          echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"

      - name: echo part
        run: |
          echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"

      ################################################
      # SETUP GO
      ################################################
      - name: Set up Go
        uses: actions/setup-go@v6.3.0
        with:
          go-version-file: "go.mod"

      - name: Display Go version
        run: go version

      - name: Install templ
        run: go install github.com/a-h/templ/cmd/templ@v0.3.1001

      - name: Generate templ files
        run: templ generate

      ################################################
      # BUILD BINARY
      ################################################
      - name: Build
        run: |
          VERSION="${{ steps.taggerDryRun.outputs.new_tag }}"
          COMMIT_SHA="${{ github.sha }}"
          BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M:%S')
          go build \
            -ldflags="-X 'main.Version=$VERSION' \
                      -X 'main.CommitSHA=$COMMIT_SHA' \
                      -X 'main.BuildDate=$BUILD_DATE'" \
            -o main.exe

      ########################################
      # TESTS
      ########################################
      - name: Test
        run: go test -v ./...

      ################################################
      # Update VERSION
      ################################################
      - name: Update version
        id: taggerFinal
        uses: anothrNick/github-tag-action@1.75.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: false

      ################################################
      # CREATE RELEASE
      ################################################
      - name: Create GitHub Release
        run: |
          TAG=${{ steps.taggerFinal.outputs.new_tag }}
          gh release create "$TAG" \
            --title "$TAG" \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ################################################
  # DEPLOY CLOUD RUN
  ################################################
  deploy:
    needs: Build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_ID_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./

      - name: Show output
        run: |
          echo "Service URL: ${{ steps.deploy.outputs.url }}"
