name: 'Build and Deploy'

on:
  pull_request:
    types:
      - closed
    branches:
      - main
    paths:
      - '**.go'
      - '**.mod'
      - '**.sum'
      - '**.templ'
      - '**.html'
      - '**.css'
      - '**.js'

concurrency: production

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0    # fetch all history
        filter: blob:none # exclude file contents for faster checkout

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.75.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # if you don't want to set write permissions use a PAT token
        WITH_V: true
        PRERELEASE: false
        DRY_RUN: true

    - name: echo new tag
      run: |
        echo "The next tag version will be: ${{ steps.taggerDryRun.outputs.new_tag }}"

    - name: echo tag
      run: |
        echo "The current tag is: ${{ steps.taggerDryRun.outputs.tag }}"

    - name: echo part
      run: |
        echo "The version increment was: ${{ steps.taggerDryRun.outputs.part }}"

    - name: Set up Go
      uses: actions/setup-go@v6.3.0
      with:
        go-version-file: 'go.mod'

    - name: Display Go version
      run: go version

    - name: Install templ
      run: go install github.com/a-h/templ/cmd/templ@v0.3.1001

    - name: Generate templ files
      run: templ generate

    - name: Build
      run: |
        VERSION="${{ steps.taggerDryRun.outputs.new_tag }}"
        COMMIT_SHA="${{ github.sha }}"
        BUILD_DATE=$(date -u +'%Y-%m-%d %H:%M:%S')
        go build -ldflags="-X 'main.Version=$VERSION' -X 'main.CommitSHA=$COMMIT_SHA' -X 'main.BuildDate=$BUILD_DATE'" -v ./...

    - name: Test
      run: go test -v ./...

    - name: Minor version for each merge
      id: taggerFinal
      uses: anothrNick/github-tag-action@1.75.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
